MediCenter3/Models/PRODUCTOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.DETALLES = new HashSet<DETALLES>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public int EXISTENCIA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public System.DateTime FECHA_VENCI { get; set; }
        public string NOTAS { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES> DETALLES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual SUCURSALES SUCURSALES { get; set; }
    }
}

MediCenter3/Controllers/PRODUCTOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MediCenter3.Models;

namespace MediCenter3.Controllers
{
    public class PRODUCTOSController : Controller
    {
        private MCEntities db = new MCEntities();

        // GET: PRODUCTOS
        public ActionResult Index()
        {
            var pRODUCTOS = db.PRODUCTOS.Include(p => p.CATEGORIAS).Include(p => p.PROVEEDORES).Include(p => p.SUCURSALES);
            return View(pRODUCTOS.ToList());
        }

        // GET: PRODUCTOS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCTOS pRODUCTOS = db.PRODUCTOS.Find(id);
            if (pRODUCTOS == null)
            {
                return HttpNotFound();
            }
            return View(pRODUCTOS);
        }

        // GET: PRODUCTOS/Create
        public ActionResult Create()
        {
            ViewBag.ID_CATEGORIA = new SelectList(db.CATEGORIAS, "ID_CATEGORIA", "CATEGORIA");
            ViewBag.ID_PROVEEDOR = new SelectList(db.PROVEEDORES, "ID_PROVEEDOR", "PROVEEDOR");
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL");
            return View();
        }

        // POST: PRODUCTOS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PRODUCTO,ID_CATEGORIA,ID_PROVEEDOR,ID_SUCURSAL,NOMBRE,PRECIO,EXISTENCIA,FECHA_INGRESO,FECHA_VENCI,NOTAS")] PRODUCTOS pRODUCTOS)
        {
            if (ModelState.IsValid)
            {
                db.PRODUCTOS.Add(pRODUCTOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_CATEGORIA = new SelectList(db.CATEGORIAS, "ID_CATEGORIA", "CATEGORIA", pRODUCTOS.ID_CATEGORIA);
            ViewBag.ID_PROVEEDOR = new SelectList(db.PROVEEDORES, "ID_PROVEEDOR", "PROVEEDOR", pRODUCTOS.ID_PROVEEDOR);
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", pRODUCTOS.ID_SUCURSAL);
            return View(pRODUCTOS);
        }

        // GET: PRODUCTOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCTOS pRODUCTOS = db.PRODUCTOS.Find(id);
            if (pRODUCTOS == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_CATEGORIA = new SelectList(db.CATEGORIAS, "ID_CATEGORIA", "CATEGORIA", pRODUCTOS.ID_CATEGORIA);
            ViewBag.ID_PROVEEDOR = new SelectList(db.PROVEEDORES, "ID_PROVEEDOR", "PROVEEDOR", pRODUCTOS.ID_PROVEEDOR);
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", pRODUCTOS.ID_SUCURSAL);
            return View(pRODUCTOS);
        }

        // POST: PRODUCTOS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PRODUCTO,ID_CATEGORIA,ID_PROVEEDOR,ID_SUCURSAL,NOMBRE,PRECIO,EXISTENCIA,FECHA_INGRESO,FECHA_VENCI,NOTAS")] PRODUCTOS pRODUCTOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pRODUCTOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_CATEGORIA = new SelectList(db.CATEGORIAS, "ID_CATEGORIA", "CATEGORIA", pRODUCTOS.ID_CATEGORIA);
            ViewBag.ID_PROVEEDOR = new SelectList(db.PROVEEDORES, "ID_PROVEEDOR", "PROVEEDOR", pRODUCTOS.ID_PROVEEDOR);
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", pRODUCTOS.ID_SUCURSAL);
            return View(pRODUCTOS);
        }

        // GET: PRODUCTOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCTOS pRODUCTOS = db.PRODUCTOS.Find(id);
            if (pRODUCTOS == null)
            {
                return HttpNotFound();
            }
            return View(pRODUCTOS);
        }

        // POST: PRODUCTOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PRODUCTOS pRODUCTOS = db.PRODUCTOS.Find(id);
            db.PRODUCTOS.Remove(pRODUCTOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MediCenter3/Views/PRODUCTOS/Create.cshtml
@model MediCenter3.Models.PRODUCTOS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PRODUCTOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_CATEGORIA, "ID_CATEGORIA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_CATEGORIA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_CATEGORIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_PROVEEDOR, "ID_PROVEEDOR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_PROVEEDOR", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PROVEEDOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_SUCURSAL, "ID_SUCURSAL", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_SUCURSAL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_SUCURSAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRECIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRECIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRECIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EXISTENCIA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EXISTENCIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EXISTENCIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_INGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_INGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_INGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_VENCI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_VENCI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_VENCI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOTAS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOTAS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOTAS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/PRODUCTOS/Delete.cshtml
@model MediCenter3.Models.PRODUCTOS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PRODUCTOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRECIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRECIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EXISTENCIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EXISTENCIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_INGRESO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_INGRESO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_VENCI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_VENCI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOTAS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOTAS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIAS.CATEGORIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIAS.CATEGORIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PROVEEDORES.PROVEEDOR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PROVEEDORES.PROVEEDOR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUCURSALES.SUCURSAL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MediCenter3/Views/PRODUCTOS/Details.cshtml
@model MediCenter3.Models.PRODUCTOS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PRODUCTOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRECIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRECIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EXISTENCIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EXISTENCIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_INGRESO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_INGRESO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_VENCI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_VENCI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOTAS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOTAS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIAS.CATEGORIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIAS.CATEGORIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PROVEEDORES.PROVEEDOR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PROVEEDORES.PROVEEDOR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUCURSALES.SUCURSAL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_PRODUCTO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MediCenter3/Views/PRODUCTOS/Edit.cshtml
@model MediCenter3.Models.PRODUCTOS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PRODUCTOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_PRODUCTO)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_CATEGORIA, "ID_CATEGORIA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_CATEGORIA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_CATEGORIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_PROVEEDOR, "ID_PROVEEDOR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_PROVEEDOR", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PROVEEDOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_SUCURSAL, "ID_SUCURSAL", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_SUCURSAL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_SUCURSAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRECIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRECIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRECIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EXISTENCIA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EXISTENCIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EXISTENCIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_INGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_INGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_INGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_VENCI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_VENCI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_VENCI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOTAS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOTAS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOTAS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/PRODUCTOS/Index.cshtml
@model IEnumerable<MediCenter3.Models.PRODUCTOS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    @Html.ActionLink("Nuevo producto", "Create", "PRODUCTOS", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PRECIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EXISTENCIA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_INGRESO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_VENCI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NOTAS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CATEGORIAS.CATEGORIA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PROVEEDORES.PROVEEDOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PRECIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EXISTENCIA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_INGRESO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_VENCI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NOTAS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORIAS.CATEGORIA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PROVEEDORES.PROVEEDOR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SUCURSALES.SUCURSAL)
        </td>
        <td>
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Edit","PRODUCTOS", new { id = item.ID_PRODUCTO  })'">Editar</button>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.ID_PRODUCTO }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Details","PRODUCTOS", new { id = item.ID_PRODUCTO })'">Detalles</button>
            @*@Html.ActionLink("Details", "Details", new { id = item.ID_PRODUCTO }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Delete","PRODUCTOS", new { id = item.ID_PRODUCTO })'">Borrar</button>
            @*@Html.ActionLink("Delete", "Delete", new { id = item.ID_PRODUCTO })*@
        </td>
    </tr>
}

</table>