MediCenter3/Models/EMPLEADOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DUI { get; set; }
    
        public virtual SUCURSALES SUCURSALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}

MediCenter3/Controllers/EMPLEADOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MediCenter3.Models;

namespace MediCenter3.Controllers
{
    public class EMPLEADOSController : Controller
    {
        private MCEntities db = new MCEntities();

        // GET: EMPLEADOS
        public ActionResult Index()
        {
            var eMPLEADOS = db.EMPLEADOS.Include(e => e.SUCURSALES);
            return View(eMPLEADOS.ToList());
        }

        // GET: EMPLEADOS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
            if (eMPLEADOS == null)
            {
                return HttpNotFound();
            }
            return View(eMPLEADOS);
        }

        // GET: EMPLEADOS/Create
        public ActionResult Create()
        {
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL");
            return View();
        }

        // POST: EMPLEADOS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_EMPLEADO,ID_SUCURSAL,NOMBRE,DUI")] EMPLEADOS eMPLEADOS)
        {
            if (ModelState.IsValid)
            {
                db.EMPLEADOS.Add(eMPLEADOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", eMPLEADOS.ID_SUCURSAL);
            return View(eMPLEADOS);
        }

        // GET: EMPLEADOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
            if (eMPLEADOS == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", eMPLEADOS.ID_SUCURSAL);
            return View(eMPLEADOS);
        }

        // POST: EMPLEADOS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_EMPLEADO,ID_SUCURSAL,NOMBRE,DUI")] EMPLEADOS eMPLEADOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eMPLEADOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_SUCURSAL = new SelectList(db.SUCURSALES, "ID_SUCURSAL", "SUCURSAL", eMPLEADOS.ID_SUCURSAL);
            return View(eMPLEADOS);
        }

        // GET: EMPLEADOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
            if (eMPLEADOS == null)
            {
                return HttpNotFound();
            }
            return View(eMPLEADOS);
        }

        // POST: EMPLEADOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
            db.EMPLEADOS.Remove(eMPLEADOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MediCenter3/Views/EMPLEADOS/Create.cshtml
@model MediCenter3.Models.EMPLEADOS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPLEADOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_SUCURSAL, "ID_SUCURSAL", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_SUCURSAL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_SUCURSAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DUI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DUI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DUI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/EMPLEADOS/Delete.cshtml
@model MediCenter3.Models.EMPLEADOS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EMPLEADOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUCURSALES.SUCURSAL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MediCenter3/Views/EMPLEADOS/Details.cshtml
@model MediCenter3.Models.EMPLEADOS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EMPLEADOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUCURSALES.SUCURSAL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_EMPLEADO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MediCenter3/Views/EMPLEADOS/Edit.cshtml
@model MediCenter3.Models.EMPLEADOS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPLEADOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_EMPLEADO)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_SUCURSAL, "ID_SUCURSAL", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_SUCURSAL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_SUCURSAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DUI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DUI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DUI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/EMPLEADOS/Index.cshtml
@model IEnumerable<MediCenter3.Models.EMPLEADOS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    @Html.ActionLink("Nuevo empleado", "Create", "EMPLEADOS", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DUI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SUCURSALES.SUCURSAL)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DUI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SUCURSALES.SUCURSAL)
        </td>
        <td>

            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Edit","EMPLEADOS", new { id = item.ID_EMPLEADO  })'">Editar</button>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.ID_EMPLEADO }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Details","EMPLEADOS", new {  id = item.ID_EMPLEADO })'">Detalles</button>
            @*@Html.ActionLink("Details", "Details", new { id = item.ID_EMPLEADO }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Delete","EMPLEADOS", new { id = item.ID_EMPLEADO })'">Borrar</button>
            @*@Html.ActionLink("Delete", "Delete", new { id = item.ID_EMPLEADO })*@
        </td>
    </tr>
}

</table>