MediCenter3/Models/CATEGORIAS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIAS()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public int ID_CATEGORIA { get; set; }
        public string CATEGORIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
    }
}

MediCenter3/Controllers/CATEGORIASController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MediCenter3.Models;

namespace MediCenter3.Controllers
{
    public class CATEGORIASController : Controller
    {
        private MCEntities db = new MCEntities();

        // GET: CATEGORIAS
        public ActionResult Index()
        {
            return View(db.CATEGORIAS.ToList());
        }

        // GET: CATEGORIAS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIAS cATEGORIAS = db.CATEGORIAS.Find(id);
            if (cATEGORIAS == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIAS);
        }

        // GET: CATEGORIAS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CATEGORIAS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_CATEGORIA,CATEGORIA")] CATEGORIAS cATEGORIAS)
        {
            if (ModelState.IsValid)
            {
                db.CATEGORIAS.Add(cATEGORIAS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cATEGORIAS);
        }

        // GET: CATEGORIAS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIAS cATEGORIAS = db.CATEGORIAS.Find(id);
            if (cATEGORIAS == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIAS);
        }

        // POST: CATEGORIAS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_CATEGORIA,CATEGORIA")] CATEGORIAS cATEGORIAS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cATEGORIAS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cATEGORIAS);
        }

        // GET: CATEGORIAS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIAS cATEGORIAS = db.CATEGORIAS.Find(id);
            if (cATEGORIAS == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIAS);
        }

        // POST: CATEGORIAS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CATEGORIAS cATEGORIAS = db.CATEGORIAS.Find(id);
            db.CATEGORIAS.Remove(cATEGORIAS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MediCenter3/Views/CATEGORIAS/Create.cshtml
@model MediCenter3.Models.CATEGORIAS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CATEGORIAS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORIA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CATEGORIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/CATEGORIAS/Delete.cshtml
@model MediCenter3.Models.CATEGORIAS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CATEGORIAS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MediCenter3/Views/CATEGORIAS/Details.cshtml
@model MediCenter3.Models.CATEGORIAS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CATEGORIAS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_CATEGORIA }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MediCenter3/Views/CATEGORIAS/Edit.cshtml
@model MediCenter3.Models.CATEGORIAS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CATEGORIAS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_CATEGORIA)

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORIA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CATEGORIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediCenter3/Views/CATEGORIAS/Index.cshtml
@model IEnumerable<MediCenter3.Models.CATEGORIAS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    @Html.ActionLink("Nueva categoria", "Create", "CATEGORIAS", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CATEGORIA)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORIA)
        </td>
        <td>
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Edit","CATEGORIAS", new { id = item.ID_CATEGORIA })'">Editar</button>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.ID_CATEGORIA }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Details","CATEGORIAS", new {  id = item.ID_CATEGORIA })'">Detalles</button>
            @*@Html.ActionLink("Details", "Details", new { id = item.ID_CATEGORIA }) |*@
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Delete","CATEGORIAS", new { id = item.ID_CATEGORIA })'">Borrar</button>
            @*@Html.ActionLink("Delete", "Delete", new { id = item.ID_CATEGORIA })*@
        </td>
    </tr>
}

</table>